/**
 * @file    ov7670_example.c
 * @brief   Complete FreeRTOS usage example for OV7670 on STM32 Nucleo F103RB.
 *
 * This file shows how to:
 *   1. Declare and initialise an OV7670_Handle.
 *   2. Start continuous capture.
 *   3. Process frames via the line_callback (low RAM path).
 *   4. Alternatively, wait for a full frame in a FreeRTOS task.
 *
 * =========================================================================
 * Integration steps in your STM32CubeIDE project
 * =========================================================================
 *
 *  a) Copy OV7670/Inc/*.h into your project's Core/Inc/ (or add the path).
 *  b) Copy OV7670/Src/*.c into your project's Core/Src/.
 *  c) In your main.c, call OV7670_Init() before vTaskStartScheduler().
 *  d) Wire OV7670_VSYNC_Callback() into HAL_GPIO_EXTI_Callback() (see below).
 *
 * =========================================================================
 * Expected CubeMX configuration
 * =========================================================================
 *   MCO (PA8)       → RCC → Master Clock Output = HSE (8 MHz)
 *   TIM2 CH1 (PA0)  → Input Capture Direct Mode
 *                      DMA → DMA1_CH5, P→M, Byte, no P-incr, M-incr
 *                      TIM2 global interrupt: Enabled, priority 5
 *                      DMA1_CH5 global interrupt: Enabled, priority 5
 *   PA2             → GPIO_EXTI2, falling edge, no pull
 *   PB0             → GPIO_Output (RESET, init HIGH)
 *   PB1             → GPIO_Output (PWDN,  init LOW)
 *   PB6             → GPIO_Output, Open-Drain (SCCB SCL)
 *   PB7             → GPIO_Output, Open-Drain (SCCB SDA)
 *   PC0–PC7         → GPIO_Input, no pull (D0–D7)
 *   FreeRTOS        → USE_PREEMPTION=1, configTICK_RATE_HZ=1000
 */

/* === User includes — adjust to match your CubeMX-generated files === */
#include "main.h"
#include "FreeRTOS.h"
#include "task.h"
#include "ov7670.h"

/* =========================================================================
 * Global camera handle — accessible from ISR and tasks
 * ========================================================================= */
static OV7670_Handle hcam;

/* =========================================================================
 * Optional: frame buffer for QQVGA RGB565 (38 400 bytes).
 * STM32F103RB has only 20 KB — this WILL NOT FIT as a static array.
 * Use the line_callback path instead (see below) and comment this out,
 * OR reduce to QQQVGA (80×60, 9 600 bytes) with a custom window config.
 *
 * Uncomment only if you have external SRAM or reduced stack/heap budgets:
 *
 * #define OV7670_USE_FRAME_BUFFER
 * #ifdef OV7670_USE_FRAME_BUFFER
 * static uint8_t s_frame_buf[160 * 120 * 2];  // 38 400 B — needs external RAM
 * #endif
 * ========================================================================= */

/* =========================================================================
 * Line callback — called from DMA ISR after each horizontal line.
 * Use this to process or forward image data without a full-frame buffer.
 *
 * Example: extract the Y (luma) channel from YUV422 and forward via UART.
 * ========================================================================= */
static void camera_line_callback(const uint8_t *line_data,
                                  uint16_t       line_num,
                                  uint16_t       width)
{
    /* Example: blink an LED on line 0 to verify timing (remove in production) */
    if (line_num == 0) {
        HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);  /* Nucleo green LED */
    }

    /*
     * For RGB565: each pixel = 2 bytes (big-endian).
     *   byte[2i]   = R[4:0] | G[5:3]
     *   byte[2i+1] = G[2:0] | B[4:0]
     *
     * Example: count pixels brighter than a threshold.
     * This runs in ISR context — keep it fast.
     */
    (void)line_data;
    (void)line_num;
    (void)width;
}

/* =========================================================================
 * Camera task — waits for complete frames and processes them
 * ========================================================================= */
#define CAMERA_TASK_STACK  256U   /* words */
#define CAMERA_TASK_PRIO   2U

static void vCameraTask(void *pvParameters)
{
    (void)pvParameters;

    /* --- Build config ---------------------------------------------------- */
    OV7670_Config cfg = {
        /* SCCB bit-bang pins */
        .sccb_scl_port = GPIOB,
        .sccb_scl_pin  = GPIO_PIN_6,
        .sccb_sda_port = GPIOB,
        .sccb_sda_pin  = GPIO_PIN_7,

        /* Hardware control */
        .reset_port = GPIOB,
        .reset_pin  = GPIO_PIN_0,
        .pwdn_port  = GPIOB,
        .pwdn_pin   = GPIO_PIN_1,

        /* Pixel data port: D0–D7 on PC0–PC7 */
        .data_port  = GPIOC,

        /* TIM2 + DMA handles generated by CubeMX (declared in main.c) */
        .htim        = &htim2,         /* extern TIM_HandleTypeDef htim2; */
        .tim_channel = TIM_CHANNEL_1,
        .hdma        = &hdma_tim2_ch1, /* extern DMA_HandleTypeDef hdma_tim2_ch1; */

        /* Image: QQVGA RGB565 */
        .resolution = OV7670_RES_QQVGA,
        .format     = OV7670_FMT_RGB565,

        /* Per-line callback for low-RAM processing */
        .line_callback  = camera_line_callback,
        .frame_callback = NULL,

        /* No full-frame buffer (comment out line_callback above if you add one) */
        .frame_buffer      = NULL,
        .frame_buffer_size = 0U,
    };

    /* --- Initialise camera ----------------------------------------------- */
    if (OV7670_Init(&hcam, &cfg) != HAL_OK) {
        /* Init failed. Check:
         *   - SCCB pull-ups present (4.7 kΩ on PB6 and PB7 to 3.3 V)?
         *   - XCLK running? (MCO on PA8, measure ~8 MHz with oscilloscope)
         *   - RESET and PWDN polarity correct?
         *   - OV7670_GetPID returns 0x7673? */
        for (;;) {
            HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
            vTaskDelay(pdMS_TO_TICKS(100));
        }
    }

    /* --- Start continuous capture --------------------------------------- */
    OV7670_StartCapture(&hcam);

    /* --- Main loop ------------------------------------------------------- */
    uint32_t frame_count = 0;

    for (;;) {
        /* Block until VSYNC fires, DMA captures all lines, semaphore is given */
        if (OV7670_WaitFrame(&hcam, pdMS_TO_TICKS(2000)) == pdTRUE) {
            frame_count++;

            /*
             * At this point:
             *   - line_callback was called once per line during capture.
             *   - If frame_buffer was provided, it contains the complete image.
             *
             * Re-arm for next frame:
             */
            OV7670_StartCapture(&hcam);

            /* Periodically print frame count via SWO/UART — example only */
            /* printf("Frame %lu captured\r\n", frame_count); */
        } else {
            /* Timeout — sensor may have stalled; re-arm */
            OV7670_StopCapture(&hcam);
            vTaskDelay(pdMS_TO_TICKS(50));
            OV7670_StartCapture(&hcam);
        }

        /* Stack watermark check during development */
        configASSERT(uxTaskGetStackHighWaterMark(NULL) > 32U);
    }
}

/* =========================================================================
 * VSYNC EXTI callback — add this inside HAL_GPIO_EXTI_Callback() in main.c
 * =========================================================================
 *
 * void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
 * {
 *     if (GPIO_Pin == GPIO_PIN_2) {          // PA2 = VSYNC
 *         OV7670_VSYNC_Callback(&hcam);
 *     }
 * }
 *
 * ========================================================================= */

/* =========================================================================
 * Task creation — call this from main() before vTaskStartScheduler()
 * ========================================================================= */
void OV7670_Example_CreateTask(void)
{
    xTaskCreate(vCameraTask,
                "Camera",
                CAMERA_TASK_STACK,
                NULL,
                CAMERA_TASK_PRIO,
                NULL);
}
